# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/beihai/Documents/ece209_lei/209-Project/OptionC/rtl/ip/dsp_mac/dsp_mac.xci
# IP: The module: 'dsp_mac' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/beihai/Documents/ece209_lei/209-Project/OptionC/rtl/ip/dsp_mac/dsp_mac_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_mac'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/beihai/Documents/ece209_lei/209-Project/OptionC/rtl/ip/dsp_mac/dsp_mac.xci
# IP: The module: 'dsp_mac' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/beihai/Documents/ece209_lei/209-Project/OptionC/rtl/ip/dsp_mac/dsp_mac_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_mac'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
